# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

FIREBASE_APP_ID = "1:190747897150:android:26a89a9d4fe583821ed06f"
FIREBASE_GROUP = "android"

platform :android do

  desc 'Distributes release apk to Firebase App Distribution'
  lane :deploy do
    # Get changelog
    changelog = prompt(
      text: 'Changelog: ',
      multi_line_end_keyword: '!!'
    )
    puts "Changelog: \n" + changelog
    changelogFinal = "production\n" + changelog

    # Build apk
    gradle(task: 'clean assembleRelease')

    # Distribute app
    firebase_app_distribution(
      app: FIREBASE_APP_ID,
      groups: FIREBASE_GROUP,
      release_notes: changelogFinal
    )
  end

end
