name: reviewdog

on: [push]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: detekt
        uses: DominuS-RU/Detekt-Action@master
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt-config.yml
          reviewdog_reporter: github-pr-check
          reviewdog_filter: nofilter
