name: test

on: [pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle command
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: test
